---
name: Docs & fmt test

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  merge_group:
  workflow_dispatch:

concurrency:
  group: docsfmttest-${{ github.event.pull_request.head.repo.full_name }}/${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docsfmttest:
    name: Docs & fmt test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: latest
          terraform_wrapper: false

      - name: Setup go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: tests/go.mod
          cache-dependency-path: tests/go.sum

      - name: Install tools
        run: make tools

      - name: Check fmt and docs
        run: |
          echo "==> Running make fmt & make docs"
          make fmt
          make docs
          echo "==> Testing for changes to tracked files"
          CHANGES=$(git status -suno)
          if [ "$CHANGES" ]; then
            echo "Repository formatting or documentation is not correct."
            echo "Run 'make fmt && make docs' locally and commit the changes to fix."
            exit 1
          fi
