---
name: Housekeeping - Cancel subscriptions
on:
  schedule:
    - cron: "11 3 * * *" # daily at 3:11
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  cancelsubscriptions:
    name: Housekeeping - Cancel subscriptions
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Azure delete subscription aliases
        uses: azure/CLI@v1
        if: always()
        continue-on-error: true
        with:
          inlineScript: |
            az rest --method GET --uri '/providers/Microsoft.Subscription/aliases/?api-version=2021-10-01' \
              | jq -r '.value[] | select(.name | test("^testdeploy")) | .name' \
              | xargs -L1 -I% az rest --method DELETE --uri '/providers/Microsoft.Subscription/aliases/%?api-version=2021-10-01'

      - name: Azure logout
        uses: azure/CLI@v1
        if: always()
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear
